In [1]:
import torch
import pandas as pd
from rouge import Rouge
from transformers import pipeline
from datasets import load_dataset
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

C:\Users\tripl\anaconda3\envs\deeplearning\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
rouge = Rouge()
dataset = load_dataset("d0r1h/ILC")
test_set = pd.DataFrame(dataset['test'])

In [3]:
test_set

,Title,Summary,Case
0,"S.86(1)(f) of the Electricity Act, is a specia...",Section 86(1)(f) vests a statutory jurisdictio...,Reportable IN THE CIVIL APPELLATE JURISDICTION...
1,"The petitioners were released on bail, as the ...",The petitioner apprehended arrest under Sectio...,IN THE HIGH COURT OF JUDICATURE AT PATNA CRIMI...
2,The allegation being only that the petitioner ...,The petitioner was arrested under Sections 344...,IN THE HIGH COURT OF JUDICATURE AT PATNA CRIMI...
3,"In service jurisprudence, seniority cannot be ...",In matters concerning administrative appointme...,IN THE HIGH COURT OF DELHI AT NEW DELHI Judgm...
4,The statute does not mandate all components of...,The facts and information of the suspected off...,on 06 04 2021 on 07 04 1606.19APPLN.odt1IN TH...
...,...,...,...
1010,Acceptance of public document could not be ref...,"In the present case, an appeal is preferred un...",IN THE HIGH COURT OF ORISSA AT CUTTACK RSA NO....
1011,Re-evaluation of answer sheets is not permissi...,Re-evaluation of answer sheets is not permissi...,IN THE HIGH COURT OF JHARKHAND AT RANCHI Kumar...
1012,Alternate accommodation for landlord alone can...,The presence of an alternate land that can be ...,IN THE HIGH COURT OF DELHI AT NEW DELHI Reser...
1013,Detention of applicant not necessary until cri...,Bail may be granted to an individual who is ac...,on 06 05 2021 on 06 05 rpa 1 5 43 ba 1355 202...
1014,Refund can be adjusted against outstanding tax...,If no notice or opportunity of pre-decisional ...,IN THE HIGH COURT OF DELHI AT NEW DELHI W.P.(C...

In [4]:
CasesText = test_set['Case'][:10]
summaryText = test_set['Summary'][:10]

In [5]:
CasesText[0]

'Reportable IN THE CIVIL APPELLATE JURISDICTION Civil Appeal No 10521 Arising out of SLP(C) No 57517) Chief General ManagerM P Power Trading Co Ltd & Anr Appellant(s) Narmada Equipments Pvt Ltd JUDGMENT Dr Dhananjaya Y Chandrachud J Leave granted. This appeal arises from a judgment and order of a learned Single Judge of the High Court of Madhya Pradesh dated 30 November 2016 where it appointed an Arbitrator in the dispute between the parties in an application1 filed by the respondent under Section 11(6) of the Arbitration and Conciliation Act 19962. The genesis of the matter is from when the Madhya Pradesh Electricity Board3 entered into a Power Purchase Agreement4 on 20 May 1999 with the respondent. “AC No 15” “1996 Act” 2 Under the PPA the respondent was to establish a mini hydro electric project on a built and operate basis. However the PPA was terminated on 27 September 2001 by the Board. The respondent initially filed a writ petition5 challenging the termination of the PPA. The High Court by its order dated 4 November 2009 declined to entertain the petition in view of an arbitration agreement contained in Clause 12.36 of the PPA. Thereafter the respondent filed a review petition7which was dismissed by the High Court by an order dated 10 December 2009. As a consequence of the orders dated 4 November 2009 and 10 December 2009 on 28 December 2009 the respondent issued a notice to the Board under Clause 12.1 of the PPA seeking to resolve the dispute by mutual discussion. Since the respondent did not receive a reply to the notice dated 28 December 2009 from the Board on 30 May 2011 the respondent issued another notice to the Board invoking arbitration under Clause 12.3 of the PPA. In the notice the respondent stated that if the Board did not act upon the notice within 30 days of its receipt it would approach the High Court under Section 11(6) of the 1996 Act. Having received no reply from the Board an application8 was filed under Section 11(6) of the 1996 Act by the respondent seeking the appointment of an arbitrator. The High Court by its order dated 21 January 2014 recorded that the respondent “WP No 26402” “12.3 Arbitration: a) If dispute cannot be salted within Thirtyby section 12.1 andto Conciliation is not elected by the Parties pursuant to Section 12.2 of if a Parties so requests in accordance with Section 12.2 the Dispute shall in dally be settled by an Umpire to be appointed by two arbitrators one to be appointed by the Board and other by the Company Provisions of the Indian Arbitration and Conciliation Act 1996 9or any enactment that replaces the said Act) shall apply in such arbitrator. The arbitration proceedings shall be held at head Quarter of the Board i.e. at Jabalpur. b) The award rendered shall apportion the costs of the arbitration. c) The award rendered in any arbitration commended here under shall be final conclusive and binding upon the Parties and award may be entered in any Court having jurisdiction as darned under article 15.1.” “Review Petition No 7109” “AC No 711” 3 and the appellant had agreed to nominate their arbitrators and observed that the two arbitrators would proceed to appoint a third arbitrator in accordance with the procedure in Clause 12.3(a) of the PPA. The nominated Arbitrators fixed their first meeting on 7 May 2014 when both parties appeared and the Arbitrators’ fee was fixed. However the Arbitrators by a letter dated 7 July 2014 highlighted their inability to proceed with the arbitration proceedings on the ground that their fees had not been paid. Thereafter the respondent filed AC No 15 on 8 December 2014 seeking the appointment of an arbitrator under Section 11(6) of the 1996 Act. This application was opposed by the appellant on the ground that in view of the provisions of Section 86(1)(f) of the Electricity Act 20039 it was the State Electricity Commission which was vested with the exclusive jurisdiction to adjudicate upon disputes between licensees and generating companies. By the impugned judgment and order dated 30 November 2016 the Single Judge of the High Court allowed the application filed by the respondent under Section 11(6) of the 1996 Act. The Single Judge held that the remedies under Section 86(1)(f) of the 2003 Act and under Section 11(6) of the 1996 Act are independent of each other and it was open to the High Court to exercise its jurisdiction under Section 11(6). The appellant now comes before this Court in appeal. The submission of the appellant which has been urged before this Court by Mr Varun Chopra learned counsel is that the view which has been taken by the High Court is contrary to the law which has been laid down by a two Judge Bench of this Court in Gujarat Urja Vikas Nigam Limited v Essar Power Limited10. “2003 Act” 2008) 4 SCC 755 hereinafter referred to as “Gujarat Urja Vikas Nigam Limited” 8 Controverting the submissions Mr Sanjay K Agrawal learned counsel appearing on behalf of the respondent however urged that the decision in Gujarat Urja Vikas Nigam Limited would not apply to the facts of the present case since the PPA was executed on 20 May 1999 and the termination by the Board was on 27 September 2001 both of these events have taken place before the enforcement of the 2003 Act on 10 June 2003. It was further urged that the appellant did not raise its objection stemming from Section 86(1)(f) of the 2003 Act when the High Court appointed Arbitrators by the consent of both parties in its order dated21 January 2014 in AC No 711 and also before the Arbitrators so appointed and hence it cannot be raised at this stage. In the present case the notice for the initiation of arbitration under Clause 12.3 of the PPA was issued by the respondent on 30 May 2011. The commencement of the arbitral proceedings by the invocation of the arbitration agreement would therefore relate to 30 May 2011 when the notice invoking Clause 12.3 was issued. Hence the fact that the PPA and the notice of termination predate the 2003 Act would not constitute material circumstances. Section 2111 of the 1996 Act specifies that unless otherwise agreed by the parties the arbitral proceedings in respect of a particular dispute would commence on the date on which a request for that dispute to be referred to arbitration is received by the respondent. Hence there can be no manner of doubt that 30 May 2011 would be the material date since it is on this date that the notice invoking Clause 12.3 was issued by the respondent to the appellant. “21. Commencement of arbitral proceedings.—Unless otherwise agreed by the parties the arbitral proceedings in respect of a particular dispute commence on the date on which a request for that dispute to be referred to arbitration is received by the respondent.” The first issue which is raised in this appeal is governed by Gujarat Urja Vikas Nigam Limitedof the 2003 Act. The Gujarat High Court thereafter appointed an Arbitrator in an application under Section 11(6) of the 1996 Act which was impugned before this Court. Speaking for the two Judge bench Justice Markandey Katju settled the position of law in paragraphs 26 27 and 28 of the judgment which are extracted below for convenience of reference: “26. It may be noted that Section 86(1)(f) of the Act of 2003 is a special provision for adjudication of disputes between the licensee and the generating companies. Such disputes can be adjudicated upon either by the State Commission or the person or persons to whom it is referred for arbitration. In our opinion the word “and” in Section 86(1)(f) between the words “generating companies” and “to refer any dispute for arbitration” means “or”. It is well settled that sometimes “and” can mean “or” and sometimes “or” can mean “and” of the Electricity Act 2003 the word “and” between the words “generating companies” and the words “refer any dispute” means “or” otherwise it will lead to an anomalous situation because obviously the State Commission cannot both decide a dispute itself and also refer it to some arbitrator. Hence the word “and” in Section 86(1)(f) means “or”. 28. Section 86(1)(f) is a special provision and hence will override the general provision in Section 11 of the Arbitration and Conciliation Act 1996 for arbitration of licensee and generating disputes between 6 companies. It is well settled that the special law overrides the general law. Hence in our opinion Section 11 of the Arbitration and Conciliation Act 1996 has no adjudicate arbitrate disputes between licensees and generating companies and only Section 86(1)(f) shall apply in such a situation.” This position has subsequently also been approved by two three Judge benches of this Court in Hindustan Zinc Limited v Ajmer Vidyut Vitran Nigam Limited12 and NHAI v Sayedabad Tea Company Limited13. From the above judgment it is evident that this Court has held that Section 86(1)(f) of the 2003 Act is a special provision which overrides the general provisions contained in Section 11 of the 1996 Act. Section 86(1)(f) vests a statutory jurisdiction with the State Electricity Commission to adjudicate upon disputes between licensees and generating companies and to refer any dispute for arbitration. The “and” between “generating companies” and “to refer any dispute for arbitration” is to be read as an “or” since the State Electricity Commission cannot obviously resolve the dispute itself and also refer it to arbitration. Section 86(1)(f) is extracted “86.Functions of State Commission.— The State Commission shall discharge the following functions namely: adjudicate upon the disputes between the licensees and generating companies and to refer any dispute for arbitration ” 2019) 17 SCC 82 hereinafter referred to as “Hindustan Zinc Limited” 2020) 15 SCC 161 7 Section 174 of the 2003 Act provides overriding effect to the 2003 Act notwithstanding anything inconsistent contained in any other law for the time being in force or in any instrument having effect by virtue of any law other than the 2003Act itself. Section 174 provides thus: “174. Act to have overriding effect. — Save as otherwise provided in Section 173 the provisions of this Act shall have effect notwithstanding anything therewith contained in any other law for the time being in force or in any instrument having effect by virtue of any law other than this Act.” We refer now to the second argument raised on behalf of the respondent that the appellant cannot raise an objection relying on Section 86(1)(f) of the 2003 Act in the second application filed by it under Section 11(6) of the 1996 Act when it had not raised the same objection in the first application under Section 11(6) of the 1996 Act or before the Arbitrators so appointed. It is pertinent to note that this argument was rejected by the Single Judge of the High Court in the impugned judgment and order dated 30 November 2016 in the following terms” “9. I will be failing in my duty if the basic objection raised by Shri Manoj Dubey about maintainability of this application is not dealt with. Merely because in earlier round of litigation the objection of maintainability was not taken it will not preclude the other side to raise such objection if it goes to the root of the matter. This is trite law that jurisdiction cannot be assumed by consent of the parties. If a statute does not provide jurisdiction to entertain an application petition the petition cannot be entertained for any reason whatsoever. Thus I am not inclined to hold that since for the reason that in the earlier round of litigation i.e. A.C. No.76 2011 parties reached to a consensus for appointment of Arbitrators this application is also maintainable. I deem it proper to examine whether because of operation of Section 174 of the Act of 2003 the present application under the Act of 1996 is not maintainable.” 8 A similar issue was raised before a three Judge bench of this Court in Hindustan Zinc Limited where an arbitrator was appointed by the State Electricity Commission under Section 86(1)(f) of the 2003 Act with the consent of the parties. Subsequently the arbitral award was challenged under Section 34 of the 1996 Act before a Commercial Court and the Commercial Court’s decision was challenged in an appeal under Section 37 of the 1996 Act where it was held that the State Electricity Commission had no jurisdiction to appoint the arbitrator since Section 86(1)(f) refers to disputes only between licensees and generating companies and not licensees and consumers. When the matter reached this Court the contention was that the objection to jurisdiction could not have been raised in a proceeding under Section 37 of the 1996 Act once the parties had consented to arbitration earlier. Speaking for the Court Justice Rohinton F Nariman held that if there is inherent lack of jurisdiction the plea can be taken at any stage and also in collateral proceedings. He highlighted the well established principle that a decree passed by a court without subject matter jurisdiction is a nullity and that its invalidity could be set up whenever and wherever it is sought to be enforced or relied upon. Such a defect of jurisdiction cannot be cured even by the consent of the parties. The above dictum would apply to the present case. In the above view of the matter the order of the High Court appointing an arbitrator under Section 11(6) of the 1996 Act is unsustainable. We accordingly allow the appeal and set aside the impugned judgment and order of the High Court dated 30 November 2016 in AC No 15. However this will not come in the way of the respondent in taking recourse to such remedies as are available in law. However we have expressed no opinion either on the merits or the 9 objections of the appellant which when urged would be considered by the appropriate forum. There shall be no order as to costs. Pending application if any stands disposed of. ….. …...…...…....... ........J. Dr Dhananjaya Y Chandrachud] M R Shah] Sanjiv Khanna] New Delhi March 23 2021 S '

In [6]:
def LEDsummarize(checkpoint,CasesText,device):

  tokenizer = AutoTokenizer.from_pretrained(checkpoint)
  model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint).to(device)
  SystemSummaries = []
  for i, case in enumerate(CasesText):
    
    input_ids = tokenizer(case, return_tensors="pt").input_ids.to(device)
    global_attention_mask = torch.zeros_like(input_ids)
    global_attention_mask[:, 0] = 1
    sequences = model.generate(input_ids, global_attention_mask=global_attention_mask)
    Summary = tokenizer.batch_decode(sequences, skip_special_tokens=True)
    SystemSummaries.append(Summary)


  return SystemSummaries

In [7]:
def summarize(checkpoint):

  """
    Helper function to summarize the text
  """
  
  tokenizer = AutoTokenizer.from_pretrained(checkpoint)
  model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint).to(device)

  SystemSummaries = []
  for i, case in enumerate(CasesText):
      
      input_ids = tokenizer(case, return_tensors="pt").input_ids.to(device)
      global_attention_mask = torch.zeros_like(input_ids)
      global_attention_mask[:, 0] = 1
      if checkpoint == "led-base-16384":
        sequences = model.generate(input_ids, global_attention_mask=global_attention_mask).sequences
      else:
        sequences = model.generate(input_ids, global_attention_mask=global_attention_mask)
      Summary = tokenizer.batch_decode(sequences, skip_special_tokens=True)

      SystemSummaries.append(Summary)
      print(i)

  return SystemSummaries

In [8]:
checkpoint = "d0r1h/led-base-ilc"
device = "cuda" if torch.cuda.is_available() else "cpu"
tokenizer1 = AutoTokenizer.from_pretrained(checkpoint)
model1 = AutoModelForSeq2SeqLM.from_pretrained(checkpoint).to(device)
#predicted_summary = LEDsummarize(checkpoint,CasesText,device)

C:\Users\tripl\anaconda3\envs\deeplearning\lib\site-packages\transformers\modeling_utils.py:1038: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(resolved_archive_file, map_location="cpu")

In [9]:
checkpoint1 = "d0r1h/led-base-ilc"
SystemSummary1 = summarize(checkpoint1)

0
1
2
3
4
5
6
7
8
9

In [14]:
predictedsummary=[]
for i in SystemSummary1:
    predictedsummary.append(i[0])

In [15]:
Summaries_result = pd.DataFrame(list(zip(summaryText, predictedsummary)), columns =['Summary', 'LEDSummary'])

In [16]:
Summaries_result.to_csv('output.csv', index=False)

In [17]:
Summaries_result

,Summary,LEDSummary
0,Section 86(1)(f) vests a statutory jurisdictio...,In the case of Gujarat Urja Vikas Nigam Limite...
1,The petitioner apprehended arrest under Sectio...,The case was taken up out of turn on the basis...
2,The petitioner was arrested under Sections 344...,The petitioner is running Dance Party from man...
3,In matters concerning administrative appointme...,The petitioners were appointed as Inspectors i...
4,The facts and information of the suspected off...,The FIR was registered on the basis of a repor...
5,"In the present strained circumstances, it is n...",The petition was filed by Sunil Dalal Sr. Adv....
6,On deciding a case regarding the contradiction...,It was contended that the advertisement prescr...
7,In the case of Parneet Kaur Vs State of Punjab...,The case was registered under section 364/ 302...
8,"Section 73 of the railway’s act, 1989 provides...",The appeal was filed under Section 23 of the R...
9,It is well settled law that this Court does no...,"In the instant case, the death of deceased Bab..."

In [18]:
score1 = rouge.get_scores(Summaries_result['LEDSummary'], Summaries_result['Summary'], avg=True)

In [19]:
pd.DataFrame(score1).set_index([['recall','precision','f-measure']])*100

             rouge-1    rouge-2    rouge-l
recall     39.303019  21.308610  36.348632
precision  47.910470  24.723998  44.378273
f-measure  42.625963  22.451412  39.452514